export const LANGUAGES = [
  { code: 'mr', label: 'मराठी' },
  { code: 'hi', label: 'हिंदी' },
  { code: 'en', label: 'English' },
  { code: 'gu', label: 'ગુજરાતી' },
  { code: 'ta', label: 'தமிழ்' },
  { code: 'bn', label: 'বাংলা' },
  { code: 'te', label: 'తెలుగు' },
];

export const TRANSLATIONS = {
  mr: {
    'logo-name': 'पवित्र ज्योतिष',
    'logo-tagline': 'स्पष्टतेचा मार्ग · २०००पासून',
    'header-hours': 'सोम–शनि: सकाळी १०:०० – रात्री ८:००',
    'hero-badge': '🌟 भारतातील विश्वसनीय ज्योतिष सेवा',
    'hero-title': 'आपल्या जीवनाचा मार्ग<br>ज्योतिषाने उजळवा',
    'hero-subtitle':
      'वैदिक ज्योतिष, कुंडली विश्लेषण आणि आध्यात्मिक मार्गदर्शनाद्वारे<br>तुमच्या जीवनात सुख, समृद्धी आणि शांतता आणा।',
    'hero-btn1': '🔭 ज्योतिषाशी बोला',
    'hero-btn2': '📜 कुंडली मिळवा',
    stat1: 'वर्षांचा अनुभव',
    stat2: 'समाधानी ग्राहक',
    stat3: 'तज्ज्ञ ज्योतिषी',
    stat4: 'भाषांमध्ये सेवा',
    stat5: 'सरासरी रेटिंग',
    'rashi-title': 'आपली राशी निवडा',
    'services-title': 'विशेष ज्योतिष सेवा',
    'nav-home': '🏠 मुखपृष्ठ',
    'nav-horoscope': '🔯 राशीभविष्य',
    'nav-services': '🌟 सेवा',
    'nav-kundali': '📜 कुंडली',
    'nav-remedies': '📅 पंचांग',
    'nav-panchang': '📅 पंचांग',
    'nav-panchang-today': 'आजचे पंचांग',
    'nav-panchang-muhurat': 'मुहूर्त',
    'nav-remedies-dosha': 'साडेसाती स्थिती',
    'nav-remedies-kaalsarp': 'कालसर्प अहवाल',
    'nav-puja': '🤝 Kundali Matching',
    'nav-consult': '🧙 ज्योतिषी',
    'nav-numerology': '🔢 अंकशास्त्र',
    'nav-contact': '📍 संपर्क',
    'reviews-title': 'ग्राहकांचे अनुभव',
    'contact-title': 'आमच्याशी संपर्क करा',
    'contact-info-title': 'संपर्क माहिती',
    'form-title': 'ज्योतिष सल्ला मागवा',
    'form-name-label': 'आपले नाव *',
    'form-phone-label': 'फोन नंबर *',
    'form-service-label': 'सेवा निवडा *',
    'form-msg-label': 'संदेश',
    'form-btn': '📨 सल्ला मागवा',
  },
  hi: {
    'logo-name': 'पवित्र ज्योतिष',
    'logo-tagline': 'स्पष्टता का मार्ग · 2000 से',
    'header-hours': 'सोम–शनि: सुबह १०:०० – रात ८:००',
    'hero-badge': '🌟 भारत की विश्वसनीय ज्योतिष सेवा',
    'hero-title': 'अपने जीवन का मार्ग<br>ज्योतिष से रोशन करें',
    'hero-subtitle':
      'वैदिक ज्योतिष, कुंडली विश्लेषण और आध्यात्मिक मार्गदर्शन से<br>अपने जीवन में सुख, समृद्धि और शांति लाएं।',
    'hero-btn1': '🔭 ज्योतिषी से बात करें',
    'hero-btn2': '📜 कुंडली प्राप्त करें',
    stat1: 'वर्षों का अनुभव',
    stat2: 'संतुष्ट ग्राहक',
    stat3: 'विशेषज्ञ ज्योतिषी',
    stat4: 'भाषाओं में सेवा',
    stat5: 'औसत रेटिंग',
    'rashi-title': 'अपनी राशि चुनें',
    'services-title': 'विशेष ज्योतिष सेवाएं',
    'nav-home': '🏠 होम',
    'nav-horoscope': '🔯 राशिफल',
    'nav-services': '🌟 सेवाएं',
    'nav-kundali': '📜 कुंडली',
    'nav-kundali-gen': 'कुंडली बनाएं',
    'nav-kundali-birth': 'जन्म कुंडली',
    'nav-kundali-planets': 'ग्रह विवरण',
    'nav-kundali-dasha': 'दशा अवधि',
    'nav-kundali-lagna-table': 'लग्न तालिका',
    'nav-remedies': '📅 पंचांग',
    'nav-puja': '🤝 कुंडली मिलान',
    'nav-panchang': '📅 पंचांग',
    'nav-panchang-today': 'आज का पंचांग',
    'nav-panchang-muhurat': 'मुहूर्त',
    'nav-panchang-hora': 'होरा',
    'nav-match': '🤝 कुंडली मिलान',
    'nav-match-kundali': 'कुंडली मिलान रिपोर्ट',
    'nav-match-ashtakoot': 'अष्टकूट मिलान',
    'nav-match-manglik': 'मांगलिक रिपोर्ट',
    'nav-remedies-dosha': 'साढ़ेसाती स्थिति',
    'nav-remedies-kaalsarp': 'कालसर्प रिपोर्ट',
    'nav-blog': '📝 ब्लॉग',
    'nav-consult': '🧙 ज्योतिषी',
    'nav-numerology': '🔢 अंकशास्त्र',
    'nav-numerology-name': 'नाम अंकशास्त्र',
    'nav-numerology-birth': 'जन्म अंक',
    'nav-numerology-destiny': 'भाग्यांक',
    'nav-contact': '📍 संपर्क',
    'reviews-title': 'ग्राहकों के अनुभव',
    'contact-title': 'हमसे संपर्क करें',
    'contact-info-title': 'संपर्क जानकारी',
    'form-title': 'ज्योतिष परामर्श लें',
    'form-name-label': 'आपका नाम *',
    'form-phone-label': 'फोन नंबर *',
    'form-service-label': 'सेवा चुनें *',
    'form-msg-label': 'संदेश',
    'form-btn': '📨 परामर्श लें',
  },
  en: {
    'logo-name': 'Pavitra Jyotish',
    'logo-tagline': 'Your Path to Clarity · Since 2000',
    'header-hours': 'Mon–Sat: 10:00 AM – 8:00 PM',
    'hero-badge': "🌟 India's Most Trusted Astrology Service",
    'hero-title': 'Illuminate Your Path<br>with the Stars',
    'hero-subtitle':
      'Through Vedic Astrology, Kundali Analysis, and Spiritual Guidance,<br>bring happiness, prosperity, and peace to your life.',
    'hero-btn1': '🔭 Talk to Astrologer',
    'hero-btn2': '📜 Get Kundali',
    stat1: 'Years Experience',
    stat2: 'Happy Clients',
    stat3: 'Expert Astrologers',
    stat4: 'Languages',
    stat5: 'Avg Rating',
    'rashi-title': 'Select Your Zodiac',
    'services-title': 'Premium Astrology Services',
    'nav-home': 'Home',
    'nav-horoscope': 'Horoscope',
    'nav-horoscope-daily': 'Daily Horoscope',
    'nav-horoscope-weekly': 'Weekly Horoscope',
    'nav-horoscope-monthly': 'Monthly Horoscope',
    'nav-horoscope-yearly': 'Yearly Horoscope',
    'nav-horoscope-moon': 'Moon Sign Calculator',
    'nav-kundali': 'Kundali',
    'nav-kundali-gen': 'Generate Kundali',
    'nav-kundali-birth': 'Birth Chart',
    'nav-kundali-planets': 'Planet Details',
    'nav-kundali-dasha': 'Dasha Period',
    'nav-kundali-lagna-table': 'Lagna Table',
    'nav-numerology': 'Numerology',
    'nav-numerology-name': 'Name Numerology',
    'nav-numerology-birth': 'Birth Number',
    'nav-numerology-destiny': 'Destiny Number',
    'nav-panchang': 'Panchang',
    'nav-panchang-today': "Today's Panchang",
    'nav-panchang-muhurat': 'Muhurat',
    'nav-panchang-hora': 'Hora',
    'nav-match': 'Kundali Matching',
    'nav-match-kundali': 'Match Kundali',
    'nav-match-ashtakoot': 'Ashtakoot Matching',
    'nav-match-manglik': 'Manglik Report',
    'nav-remedies': 'Remedies',
    'nav-remedies-dosha': 'Sade Sati Status',
    'nav-remedies-kaalsarp': 'Kaal Sarp Report',
    'nav-blog': 'Blog',
    'nav-contact': 'Contact',
    'reviews-title': 'Client Testimonials',
    'contact-title': 'Contact Us',
    'contact-info-title': 'Contact Information',
    'form-title': 'Request Consultation',
    'form-name-label': 'Your Name *',
    'form-phone-label': 'Phone Number *',
    'form-service-label': 'Select Service *',
    'form-msg-label': 'Message',
    'form-btn': '📨 Request Consultation',
  },
  gu: {
    'logo-name': 'પવિત્ર જ્યોતિષ',
    'logo-tagline': 'સ્પષ્ટતાનો માર્ગ · 2000 થી',
    'header-hours': 'સોમ–શનિ: સવારે ૧૦:૦૦ – રાત ૮:૦૦',
    'hero-badge': '🌟 ભારતની વિશ્વસનીય જ્યોતિષ સેવા',
    'hero-title': 'આપના જીવનનો માર્ગ<br>જ્યોતિષ વડે ઉજ્વળ કરો',
    'hero-subtitle':
      'વૈદિક જ્યોતિષ, કુંડળી વિશ્લેષણ અને આધ્યાત્મિક માર્ગદર્શન<br>દ્વારા તમારા જીવનમાં સુખ, સમૃદ્ધિ અને શાંતિ લાવો।',
    'hero-btn1': '🔭 જ્યોતિષી સાથે વાત કરો',
    'hero-btn2': '📜 કુંડળી મેળવો',
    stat1: 'વર્ષોનો અનુભવ',
    stat2: 'સંતુષ્ટ ગ્રાહકો',
    stat3: 'નિષ્ણાત જ્યોતિષી',
    stat4: 'ભાષાઓમાં સેવા',
    stat5: 'સ્ટાર રેટિંગ',
    'rashi-title': 'આપની રાશિ પસંદ કરો',
    'services-title': 'વિશેષ જ્યોતિષ સેવાઓ',
    'nav-home': '🏠 હોમ',
    'nav-horoscope': '🔯 રાશિભવિષ્ય',
    'nav-services': '🌟 સેવાઓ',
    'nav-kundali': '📜 કુંડળી',
    'nav-remedies': '📅 પંચાંગ',
    'nav-puja': '🤝 Kundali Matching',
    'nav-consult': '🧙 જ્યોતિષી',
    'nav-contact': '📍 સંપર્ક',
    'reviews-title': 'ગ્રાહકોના અનુભવ',
    'contact-title': 'અમારો સંપર્ક કરો',
    'contact-info-title': 'સંપર્ક માહિતી',
    'form-title': 'જ્યોતિષ સલાહ લો',
    'form-name-label': 'આપનું નામ *',
    'form-phone-label': 'ફોન નંબર *',
    'form-service-label': 'સેવા પસંદ કરો *',
    'form-msg-label': 'સંદેશ',
    'form-btn': '📨 સલાહ લો',
  },
  ta: {
    'logo-name': 'பவித்ர ஜோதிஷ்',
    'logo-tagline': 'தெளிவுக்கான பாதை · 2000 முதல்',
    'header-hours': 'திங்கள்–சனி: காலை 10:00 – இரவு 8:00',
    'hero-badge': '🌟 இந்தியாவின் நம்பகமான ஜோதிட சேவை',
    'hero-title': 'உங்கள் வாழ்க்கை பாதையை<br>ஜோதிடத்தால் ஒளிர்விக்கவும்',
    'hero-subtitle':
      'வேத ஜோதிடம், குண்டலி பகுப்பாய்வு மற்றும்<br>ஆன்மீக வழிகாட்டுதல் மூலம் வாழ்வில் மகிழ்ச்சி பெறுங்கள்।',
    'hero-btn1': '🔭 ஜோதிடரிடம் பேசுங்கள்',
    'hero-btn2': '📜 ஜாதகம் பெறுங்கள்',
    stat1: 'ஆண்டுகள் அனுபவம்',
    stat2: 'மகிழ்ச்சியான வாடிக்கையாளர்கள்',
    stat3: 'நிபுணர் ஜோதிடர்கள்',
    stat4: 'மொழிகளில் சேவை',
    stat5: 'சராசரி மதிப்பீடு',
    'rashi-title': 'உங்கள் ராசியை தேர்ந்தெடுக்கவும்',
    'services-title': 'சிறப்பு ஜோதிட சேவைகள்',
    'nav-home': '🏠 முகப்பு',
    'nav-horoscope': '🔯 ஜாதகம்',
    'nav-services': '🌟 சேவைகள்',
    'nav-kundali': '📜 குண்டலி',
    'nav-remedies': '📅 பஞ்சாங்கம்',
    'nav-puja': '🤝 Kundali Matching',
    'nav-consult': '🧙 ஜோதிடர்',
    'nav-contact': '📍 தொடர்பு',
    'reviews-title': 'வாடிக்கையாளர் கருத்துகள்',
    'contact-title': 'எங்களை தொடர்பு கொள்ளுங்கள்',
    'contact-info-title': 'தொடர்பு தகவல்',
    'form-title': 'ஜோதிட ஆலோசனை பெறுங்கள்',
    'form-name-label': 'உங்கள் பெயர் *',
    'form-phone-label': 'தொலைபேசி எண் *',
    'form-service-label': 'சேவை தேர்ந்தெடுக்கவும் *',
    'form-msg-label': 'செய்தி',
    'form-btn': '📨 ஆலோசனை பெறுங்கள்',
  },
  bn: {
    'logo-name': 'পবিত্র জ্যোতিষ',
    'logo-tagline': 'স্পষ্টতার পথ · ২০০০ সাল থেকে',
    'header-hours': 'সোম–শনি: সকাল ১০:০০ – রাত ৮:০০',
    'hero-badge': '🌟 ভারতের বিশ্বস্ত জ্যোতিষ সেবা',
    'hero-title': 'আপনার জীবনের পথ<br>জ্যোতিষ দিয়ে আলোকিত করুন',
    'hero-subtitle':
      'বৈদিক জ্যোতিষ, কুণ্ডলী বিশ্লেষণ এবং আধ্যাত্মিক নির্দেশনার মাধ্যমে<br>জীবনে সুখ, সমৃদ্ধি এবং শান্তি আনুন।',
    'hero-btn1': '🔭 জ্যোতিষীর সাথে কথা বলুন',
    'hero-btn2': '📜 কুণ্ডলী পান',
    stat1: 'বছরের অভিজ্ঞতা',
    stat2: 'সন্তুষ্ট গ্রাহক',
    stat3: 'বিশেষজ্ঞ জ্যোতিষী',
    stat4: 'ভাষায় সেবা',
    stat5: 'গড় রেটিং',
    'rashi-title': 'আপনার রাশি বেছে নিন',
    'services-title': 'বিশেষ জ্যোতিষ সেবা',
    'nav-home': '🏠 হোম',
    'nav-horoscope': '🔯 রাশিফল',
    'nav-services': '🌟 সেবা',
    'nav-kundali': '📜 কুণ্ডলী',
    'nav-remedies': '📅 পঞ্চাঙ্গ',
    'nav-puja': '🤝 Kundali Matching',
    'nav-consult': '🧙 জ্যোতিষী',
    'nav-contact': '📍 যোগাযোগ',
    'reviews-title': 'গ্রাহকদের অভিজ্ঞতা',
    'contact-title': 'আমাদের সাথে যোগাযোগ করুন',
    'contact-info-title': 'যোগাযোগের তথ্য',
    'form-title': 'জ্যোতিষ পরামর্শ নিন',
    'form-name-label': 'আপনার নাম *',
    'form-phone-label': 'ফোন নম্বর *',
    'form-service-label': 'সেবা বেছে নিন *',
    'form-msg-label': 'বার্তা',
    'form-btn': '📨 পরামর্শ নিন',
  },
  te: {
    'logo-name': 'పవిత్ర జ్యోతిష్',
    'logo-tagline': 'స్పష్టత మార్గం · 2000 నుండి',
    'header-hours': 'సోమ–శని: ఉదయం 10:00 – రాత్రి 8:00',
    'hero-badge': '🌟 భారతదేశంలో విశ్వసనీయ జ్యోతిష్య సేవ',
    'hero-title': 'మీ జీవన మార్గాన్ని<br>జ్యోతిష్యంతో వెలిగించండి',
    'hero-subtitle':
      'వేద జ్యోతిష్యం, కుండలి విశ్లేషణ మరియు ఆధ్యాత్మిక మార్గదర్శకత్వంతో<br>జీవితంలో సంతోషం, సమృద్ధి మరియు శాంతి తీసుకురండి।',
    'hero-btn1': '🔭 జ్యోతిషుడితో మాట్లాడండి',
    'hero-btn2': '📜 కుండలి పొందండి',
    stat1: 'సంవత్సరాల అనుభవం',
    stat2: 'సంతుష్ట వినియోగదారులు',
    stat3: 'నిపుణ జ్యోతిషులు',
    stat4: 'భాషలలో సేవ',
    stat5: 'సగటు రేటింగ్',
    'rashi-title': 'మీ రాశిని ఎంచుకోండి',
    'services-title': 'విశేష జ్యోతిష్య సేవలు',
    'nav-home': '🏠 హోమ్',
    'nav-horoscope': '🔯 జాతకం',
    'nav-services': '🌟 సేవలు',
    'nav-kundali': '📜 కుండలి',
    'nav-remedies': '📅 పంచాంగం',
    'nav-puja': '🤝 Kundali Matching',
    'nav-consult': '🧙 జ్యోతిషులు',
    'nav-contact': '📍 సంప్రదింపు',
    'reviews-title': 'వినియోగదారుల అనుభవాలు',
    'contact-title': 'మమ్మల్ని సంప్రదించండి',
    'contact-info-title': 'సంప్రదింపు సమాచారం',
    'form-title': 'జ్యోతిష్య సలహా పొందండి',
    'form-name-label': 'మీ పేరు *',
    'form-phone-label': 'ఫోన్ నంబర్ *',
    'form-service-label': 'సేవ ఎంచుకోండి *',
    'form-msg-label': 'సందేశం',
    'form-btn': '📨 సలహా పొందండి',
  },
};

export const NAV_ITEMS = [
  { key: 'nav-home', to: '/', icon: 'Home' },
  { 
    key: 'nav-kundali', 
    to: '/kundali',
    icon: 'ScrollText',
    children: [
      { key: 'nav-kundali-gen', to: '/kundali/generate' },
      { key: 'nav-kundali-birth', to: '/kundali/birth-chart' },
      { key: 'nav-kundali-planets', to: '/kundali/planets' },
      { key: 'nav-kundali-dasha', to: '/kundali/dasha' },
    ]
  },
  { 
    key: 'nav-kundali-lagna-table', 
    to: '/kundali/lagna-intervals',
    icon: 'BarChart4'
  },
  { 
    key: 'nav-numerology', 
    to: '/numerology',
    icon: 'Binary'
  },
  { 
    key: 'nav-panchang', 
    to: '/panchang',
    icon: 'CalendarDays',
    children: [
      { key: 'nav-panchang-today', to: '/panchang/today' },
      { key: 'nav-panchang-muhurat', to: '/panchang/muhurat' },
      { key: 'nav-remedies-dosha', to: '/remedies/sadesati' },
      { key: 'nav-remedies-kaalsarp', to: '/remedies/kaalsarp' },
    ]
  },
  { 
    key: 'nav-match', 
    to: '/match',
    icon: 'Link2',
    children: [
      { key: 'nav-match-kundali', to: '/match/kundali' },
      { key: 'nav-match-ashtakoot', to: '/match/ashtakoot' },
      { key: 'nav-match-manglik', to: '/match/manglik' },
    ]
  },
  { key: 'nav-blog', to: '/blog', icon: 'BookText' },
  { key: 'nav-contact', to: '/contact', icon: 'Phone' },
];

export const RASHI_DATA = [
  { key: 'Mesh', symbol: '♈', hi: 'मेष', en: 'ARIES', dates: 'Mar 21 – Apr 19' },
  { key: 'Vrishabh', symbol: '♉', hi: 'वृषभ', en: 'TAURUS', dates: 'Apr 20 – May 20' },
  { key: 'Mithun', symbol: '♊', hi: 'मिथुन', en: 'GEMINI', dates: 'May 21 – Jun 20' },
  { key: 'Kark', symbol: '♋', hi: 'कर्क', en: 'CANCER', dates: 'Jun 21 – Jul 22' },
  { key: 'Singh', symbol: '♌', hi: 'सिंह', en: 'LEO', dates: 'Jul 23 – Aug 22' },
  { key: 'Kanya', symbol: '♍', hi: 'कन्या', en: 'VIRGO', dates: 'Aug 23 – Sep 22' },
  { key: 'Tula', symbol: '♎', hi: 'तुला', en: 'LIBRA', dates: 'Sep 23 – Oct 22' },
  { key: 'Vrishchik', symbol: '♏', hi: 'वृश्चिक', en: 'SCORPIO', dates: 'Oct 23 – Nov 21' },
  { key: 'Dhanu', symbol: '♐', hi: 'धनु', en: 'SAGITTARIUS', dates: 'Nov 22 – Dec 21' },
  { key: 'Makar', symbol: '♑', hi: 'मकर', en: 'CAPRICORN', dates: 'Dec 22 – Jan 19' },
  { key: 'Kumbh', symbol: '♒', hi: 'कुंभ', en: 'AQUARIUS', dates: 'Jan 20 – Feb 18' },
  { key: 'Meen', symbol: '♓', hi: 'मीन', en: 'PISCES', dates: 'Feb 19 – Mar 20' },
];

export const TICKER_ITEMS = [
  '🌟 आजचे राशीभविष्य उपलब्ध आहे',
  'आजचा राशिफल उपलब्ध है',
  "Today's Horoscope Available",
  '🔴 विशेष ऑफर: ज्योतिष परामर्श पर 30% छूट',
  'New: Kundali Matching Now Available',
  '🌙 चंद्र ग्रहण विशेष पूजा – बुकिंग सुरू',
];
